### ISSUE TITLE
You're under arrest!!

### ISSUE THREAD

**Issue by abhi18av** [emilyncosta/eai-genome#1]
@emilyncosta , this is issued in public interest that you're too beautiful to be a programmer on GitHub, strict action shall be taken.

The Interpol has been informed of the severity of this crime, and we assure you, all your actions are being tracked from now on.

When you're arrested your delicious cheeks will be sentenced to a lifetime of kisses and  love.

You can run but you cannot hide 😎

**Comment by emilyncosta** [comment]
Dear @abhi18av, do you realize how cute you are and how I still don't know how to use this website properly? Hahaha... Well, it seems that I am a good lier and you are a poetry, my dear. ^^

**Comment by abhi18av** [comment]
@emilyncosta , my queen I shall resolve this issue now  😚😙😗😘
